### ISSUE TITLE
Podcast apps not recognizing episodes

### ISSUE THREAD

**Issue by nicknisi** [jhannah/jayflaunts#1]
I'm not sure if there is a particular RSS format that the episodes need to be delivered in, but podcast apps can't seem to find the episodes. Doing a search for your podcast, it does seem to find it, but there are no episodes listed.

![img_0681](https://cloud.githubusercontent.com/assets/293805/5789908/b98883bc-9e44-11e4-84a9-30b8c06db456.PNG)

**Comment by jhannah** [comment]
Hmm... Does FeedBurner work? http://feeds.feedburner.com/JayFlaunts

**Comment by jhannah** [comment]
And/or maybe I need to add 2 fields to my Jekyll markdown...? http://www.adamwilcox.org/2013/01/17/from-the-pub/ What app are you using?

**Comment by nicknisi** [comment]
Thanks! The FeedBurner link worked! I am using Instacast.
